
package br.com.tqi.company.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CompanyServicesService", targetNamespace = "http://services.company.tqi.com.br/", wsdlLocation = "http://localhost:8080/CompanyServicesService/CompanyServices?wsdl#%7Bhttp%3A%2F%2Fservices.company.tqi.com.br%2F%7DCompanyServicesService")
public class CompanyServicesService
    extends Service
{

    private final static URL COMPANYSERVICESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.tqi.company.ws.CompanyServicesService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.tqi.company.ws.CompanyServicesService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/CompanyServicesService/CompanyServices?wsdl#%7Bhttp%3A%2F%2Fservices.company.tqi.com.br%2F%7DCompanyServicesService");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/CompanyServicesService/CompanyServices?wsdl#%7Bhttp%3A%2F%2Fservices.company.tqi.com.br%2F%7DCompanyServicesService', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COMPANYSERVICESSERVICE_WSDL_LOCATION = url;
    }

    public CompanyServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompanyServicesService() {
        super(COMPANYSERVICESSERVICE_WSDL_LOCATION, new QName("http://services.company.tqi.com.br/", "CompanyServicesService"));
    }

    /**
     * 
     * @return
     *     returns CompanyServices
     */
    @WebEndpoint(name = "CompanyServicesPort")
    public CompanyServices getCompanyServicesPort() {
        return super.getPort(new QName("http://services.company.tqi.com.br/", "CompanyServicesPort"), CompanyServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompanyServices
     */
    @WebEndpoint(name = "CompanyServicesPort")
    public CompanyServices getCompanyServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.company.tqi.com.br/", "CompanyServicesPort"), CompanyServices.class, features);
    }

}
