
package br.com.tqi.company.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.com.tqi.company.ws.client.City;
import br.com.tqi.company.ws.client.Company;
import br.com.tqi.company.ws.client.ObjectFactory;
import br.com.tqi.company.ws.client.State;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CompanyServices", targetNamespace = "http://services.company.tqi.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CompanyServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.tqi.company.ws.client.Company
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCompany", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.AddCompany")
    @ResponseWrapper(localName = "addCompanyResponse", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.AddCompanyResponse")
    public Company addCompany(
        @WebParam(name = "arg0", targetNamespace = "")
        Company arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateCompany", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.UpdateCompany")
    @ResponseWrapper(localName = "updateCompanyResponse", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.UpdateCompanyResponse")
    public void updateCompany(
        @WebParam(name = "arg0", targetNamespace = "")
        Company arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteCompany", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.DeleteCompany")
    @ResponseWrapper(localName = "deleteCompanyResponse", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.DeleteCompanyResponse")
    public void deleteCompany(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<br.com.tqi.company.ws.client.Company>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCompanies", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.ListCompanies")
    @ResponseWrapper(localName = "listCompaniesResponse", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.ListCompaniesResponse")
    public List<Company> listCompanies(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.tqi.company.ws.client.State>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listStates", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.ListStates")
    @ResponseWrapper(localName = "listStatesResponse", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.ListStatesResponse")
    public List<State> listStates();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<br.com.tqi.company.ws.client.City>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCities", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.ListCities")
    @ResponseWrapper(localName = "listCitiesResponse", targetNamespace = "http://services.company.tqi.com.br/", className = "br.com.tqi.company.ws.client.ListCitiesResponse")
    public List<City> listCities(
        @WebParam(name = "arg0", targetNamespace = "")
        State arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
